


ENV['VAGRANT_DEFAULT_PROVIDER'] = 'docker'
 
Vagrant.configure("2") do |config|
 
config.vm.define "nginx-container" do |m|
 
m.vm.provider :docker do |d|
d.build_dir = "."
d.cmd = ["ping", "-c 51", "127.0.0.1"]
d.remains_running = true
d.cmd = ["/bin/bash", "-l"]
d.has_ssh = true
d.vagrant_machine = "dockerhostvm"
d.vagrant_vagrantfile = "./DockerHostVagrantfile"
config.vm.provision :shell, path: "bootstrap.sh"

end
end
end
