
Vagrant.configure(2) do |config|
#installing centos/7
	config.vm.define "dockerhostvmtask2"
	config.vm.box = "centos/7"
	config.vm.synced_folder ".", "/vagrant", type: "virtualbox"
	config.vm.network "public_network"

	
	config.vm.provision "ansible" do |ansible|
		ansible.verbose = "v"
		ansible.playbook = "nginx.yml"
	end
	
 
end